### ISSUE TITLE
Not crashing!

### ISSUE THREAD

**Issue by Dylan5797** [Dylan5797/ScratchEdit#10]
ScratchEdit won't crash because ```fatalErr``` is passed instead of ```errText``` in the subprocess line

**Comment by wizzwizz4** [comment]
Sorry!

**Comment by Dylan5797** [comment]
It's fine, I'd make mistakes like that if I didn't test it out. I used sys.exit() in a try statement, and sys.exit() just raises an error that isn't displayed to stop the program. Use os._exit(1) it finds the PID of python and kills it
