### ISSUE TITLE
Beta Version Numbering

### ISSUE THREAD

**Issue by wizzwizz4** [Dylan5797/ScratchEdit#11]
Versions 3.2 and 3.3 are identical...

**Comment by wizzwizz4** [comment]
And shouldn't it be Version 3.0.2 and 3.0.3 etc?

**Comment by Dylan5797** [comment]
I don't know, and sorry, I had no internet for the last five days

**Comment by Dylan5797** [comment]
I must have updated it before I made the version tag!

**Comment by Dylan5797** [comment]
I'm fixing the 3.0.2 etc. and the beta indication.

**Comment by wizzwizz4** [comment]
Bump. I've assigned you to the task as I have no knowledge of v3.2-beta.

**Comment by Dylan5797** [comment]
Done.
