### ISSUE TITLE
GUI only!

### ISSUE THREAD

**Issue by wizzwizz4** [Dylan5797/ScratchEdit#4]
Rename, using the website, the ScratchEdit.py file to ScratchEdit.pyw (so it counts as rename, not file creation and deletion). One of the main benefits of the new version was console-less-ness!

**Comment by Dylan5797** [comment]
Oh! I forgot! Thanks!

**Comment by Dylan5797** [comment]
Fixed it!

**Comment by wizzwizz4** [comment]
@Dylan5797 You need to change the README.md as well!
Off-topic: The Wiki is open to editing by everybody. This could cause some issues if somebody (whether intentionally or not) makes unconstructive edits. However, I would still like to contribute if you do feel the need to change this.
